/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppOutletRouteImport } from './routes/app.outlet'
import { Route as AppHqRouteImport } from './routes/app.hq'
import { Route as AppOutletIndexRouteImport } from './routes/app.outlet.index'
import { Route as AppHqIndexRouteImport } from './routes/app.hq.index'
import { Route as AppOutletSalesRouteImport } from './routes/app.outlet.sales'
import { Route as AppOutletInventoryRouteImport } from './routes/app.outlet.inventory'
import { Route as AppOutletHistoryRouteImport } from './routes/app.outlet.history'
import { Route as AppHqReportsRouteImport } from './routes/app.hq.reports'
import { Route as AppHqProductsRouteImport } from './routes/app.hq.products'
import { Route as AppHqOutletsOutletIdRouteImport } from './routes/app.hq.outlets.$outletId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOutletRoute = AppOutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => AppRoute,
} as any)
const AppHqRoute = AppHqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => AppRoute,
} as any)
const AppOutletIndexRoute = AppOutletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOutletRoute,
} as any)
const AppHqIndexRoute = AppHqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHqRoute,
} as any)
const AppOutletSalesRoute = AppOutletSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppOutletRoute,
} as any)
const AppOutletInventoryRoute = AppOutletInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppOutletRoute,
} as any)
const AppOutletHistoryRoute = AppOutletHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppOutletRoute,
} as any)
const AppHqReportsRoute = AppHqReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppHqRoute,
} as any)
const AppHqProductsRoute = AppHqProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppHqRoute,
} as any)
const AppHqOutletsOutletIdRoute = AppHqOutletsOutletIdRouteImport.update({
  id: '/outlets/$outletId',
  path: '/outlets/$outletId',
  getParentRoute: () => AppHqRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/hq': typeof AppHqRouteWithChildren
  '/app/outlet': typeof AppOutletRouteWithChildren
  '/app/hq/products': typeof AppHqProductsRoute
  '/app/hq/reports': typeof AppHqReportsRoute
  '/app/outlet/history': typeof AppOutletHistoryRoute
  '/app/outlet/inventory': typeof AppOutletInventoryRoute
  '/app/outlet/sales': typeof AppOutletSalesRoute
  '/app/hq/': typeof AppHqIndexRoute
  '/app/outlet/': typeof AppOutletIndexRoute
  '/app/hq/outlets/$outletId': typeof AppHqOutletsOutletIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/hq/products': typeof AppHqProductsRoute
  '/app/hq/reports': typeof AppHqReportsRoute
  '/app/outlet/history': typeof AppOutletHistoryRoute
  '/app/outlet/inventory': typeof AppOutletInventoryRoute
  '/app/outlet/sales': typeof AppOutletSalesRoute
  '/app/hq': typeof AppHqIndexRoute
  '/app/outlet': typeof AppOutletIndexRoute
  '/app/hq/outlets/$outletId': typeof AppHqOutletsOutletIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/hq': typeof AppHqRouteWithChildren
  '/app/outlet': typeof AppOutletRouteWithChildren
  '/app/hq/products': typeof AppHqProductsRoute
  '/app/hq/reports': typeof AppHqReportsRoute
  '/app/outlet/history': typeof AppOutletHistoryRoute
  '/app/outlet/inventory': typeof AppOutletInventoryRoute
  '/app/outlet/sales': typeof AppOutletSalesRoute
  '/app/hq/': typeof AppHqIndexRoute
  '/app/outlet/': typeof AppOutletIndexRoute
  '/app/hq/outlets/$outletId': typeof AppHqOutletsOutletIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/hq'
    | '/app/outlet'
    | '/app/hq/products'
    | '/app/hq/reports'
    | '/app/outlet/history'
    | '/app/outlet/inventory'
    | '/app/outlet/sales'
    | '/app/hq/'
    | '/app/outlet/'
    | '/app/hq/outlets/$outletId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/hq/products'
    | '/app/hq/reports'
    | '/app/outlet/history'
    | '/app/outlet/inventory'
    | '/app/outlet/sales'
    | '/app/hq'
    | '/app/outlet'
    | '/app/hq/outlets/$outletId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/hq'
    | '/app/outlet'
    | '/app/hq/products'
    | '/app/hq/reports'
    | '/app/outlet/history'
    | '/app/outlet/inventory'
    | '/app/outlet/sales'
    | '/app/hq/'
    | '/app/outlet/'
    | '/app/hq/outlets/$outletId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/outlet': {
      id: '/app/outlet'
      path: '/outlet'
      fullPath: '/app/outlet'
      preLoaderRoute: typeof AppOutletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hq': {
      id: '/app/hq'
      path: '/hq'
      fullPath: '/app/hq'
      preLoaderRoute: typeof AppHqRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outlet/': {
      id: '/app/outlet/'
      path: '/'
      fullPath: '/app/outlet/'
      preLoaderRoute: typeof AppOutletIndexRouteImport
      parentRoute: typeof AppOutletRoute
    }
    '/app/hq/': {
      id: '/app/hq/'
      path: '/'
      fullPath: '/app/hq/'
      preLoaderRoute: typeof AppHqIndexRouteImport
      parentRoute: typeof AppHqRoute
    }
    '/app/outlet/sales': {
      id: '/app/outlet/sales'
      path: '/sales'
      fullPath: '/app/outlet/sales'
      preLoaderRoute: typeof AppOutletSalesRouteImport
      parentRoute: typeof AppOutletRoute
    }
    '/app/outlet/inventory': {
      id: '/app/outlet/inventory'
      path: '/inventory'
      fullPath: '/app/outlet/inventory'
      preLoaderRoute: typeof AppOutletInventoryRouteImport
      parentRoute: typeof AppOutletRoute
    }
    '/app/outlet/history': {
      id: '/app/outlet/history'
      path: '/history'
      fullPath: '/app/outlet/history'
      preLoaderRoute: typeof AppOutletHistoryRouteImport
      parentRoute: typeof AppOutletRoute
    }
    '/app/hq/reports': {
      id: '/app/hq/reports'
      path: '/reports'
      fullPath: '/app/hq/reports'
      preLoaderRoute: typeof AppHqReportsRouteImport
      parentRoute: typeof AppHqRoute
    }
    '/app/hq/products': {
      id: '/app/hq/products'
      path: '/products'
      fullPath: '/app/hq/products'
      preLoaderRoute: typeof AppHqProductsRouteImport
      parentRoute: typeof AppHqRoute
    }
    '/app/hq/outlets/$outletId': {
      id: '/app/hq/outlets/$outletId'
      path: '/outlets/$outletId'
      fullPath: '/app/hq/outlets/$outletId'
      preLoaderRoute: typeof AppHqOutletsOutletIdRouteImport
      parentRoute: typeof AppHqRoute
    }
  }
}

interface AppHqRouteChildren {
  AppHqProductsRoute: typeof AppHqProductsRoute
  AppHqReportsRoute: typeof AppHqReportsRoute
  AppHqIndexRoute: typeof AppHqIndexRoute
  AppHqOutletsOutletIdRoute: typeof AppHqOutletsOutletIdRoute
}

const AppHqRouteChildren: AppHqRouteChildren = {
  AppHqProductsRoute: AppHqProductsRoute,
  AppHqReportsRoute: AppHqReportsRoute,
  AppHqIndexRoute: AppHqIndexRoute,
  AppHqOutletsOutletIdRoute: AppHqOutletsOutletIdRoute,
}

const AppHqRouteWithChildren = AppHqRoute._addFileChildren(AppHqRouteChildren)

interface AppOutletRouteChildren {
  AppOutletHistoryRoute: typeof AppOutletHistoryRoute
  AppOutletInventoryRoute: typeof AppOutletInventoryRoute
  AppOutletSalesRoute: typeof AppOutletSalesRoute
  AppOutletIndexRoute: typeof AppOutletIndexRoute
}

const AppOutletRouteChildren: AppOutletRouteChildren = {
  AppOutletHistoryRoute: AppOutletHistoryRoute,
  AppOutletInventoryRoute: AppOutletInventoryRoute,
  AppOutletSalesRoute: AppOutletSalesRoute,
  AppOutletIndexRoute: AppOutletIndexRoute,
}

const AppOutletRouteWithChildren = AppOutletRoute._addFileChildren(
  AppOutletRouteChildren,
)

interface AppRouteChildren {
  AppHqRoute: typeof AppHqRouteWithChildren
  AppOutletRoute: typeof AppOutletRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppHqRoute: AppHqRouteWithChildren,
  AppOutletRoute: AppOutletRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
